### ISSUE TITLE
Level messages extend past visual boundry and obscure Level Select dropdown box in Firefox

### ISSUE THREAD

**Issue by RenateStrind** [Will9371/Digital_Logic_Game#7]
on certain levels the Level message extends past the border,
Boolean Logic 3
Reading Truth Tables

Not a problem in Internet explorer.

**Comment by Will9371** [comment]
Fixed by modifying values in DigitalLogic.CSS.css to increase size of text box (and lower level select box)

Ln71: top changed from 330 to 340
Ln98: height changed from 240 to 250

There is still plenty of space above the Step, Run, and Reset buttons, so the text box can be further expanded if need be.
